import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
const space = Space_Grotesk({ subsets: ["latin"], variable: "--font-space" });
export const metadata: Metadata = {
  title: "Positive | مثبت",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${space.variable}`}>
        <div className="min-h-screen font-space container-padding max-container">{children}</div>
      </body>
    </html>
  );
}
